services:
  app:
    image: solar-watch-docker-compose-java-mariannamolnar-app:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - solarwatch.geocode.api.key=${API_KEY}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/solarwatch
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - codecool.app.jwtSecret=${JWT_SECRET}
      - codecool.app.jwtExpirationMs=${jwtExpirationMs}



  db:
    image: 'postgres:13.1-alpine'
    #ports:
    #  - '5432' #psql port, de a db-hez nem kell port, mert nem akarjuk kívülről elérni
    container_name: db
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=solarwatch
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    depends_on:
      - app
    ports:
      - "80:80"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend


volumes:
  postgres_data: